# wrangler.toml

name = "onecash1"
main = "public/index.js"
compatibility_date = "2025-11-10"

# Fill your Cloudflare account id here
# Get it from https://dash.cloudflare.com/profile -> Account ID
account_id = "a328417757a47bec333a97b113059228"



[build]
upload_format = "service-worker"

[vars]
# Nothing secret here; use `wrangler secret put` or dashboard Secrets to set secrets
# Example: wrangler secret put SECRET_NOW_API_KEY
